# Generated by Django 2.0.5 on 2018-06-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='aboutmo',
            new_name='aboutme',
        ),
    ]
