# Generated by Django 2.0.6 on 2018-07-15 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180714_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 1, 24, 21, 401281, tzinfo=utc)),
        ),
    ]
