# Generated by Django 2.0.6 on 2018-07-16 01:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180715_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 1, 55, 6, 169886, tzinfo=utc)),
        ),
    ]
