# Generated by Django 2.0.6 on 2018-07-27 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grout',
            name='grout_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 27, 14, 44, 23, 811664, tzinfo=utc)),
        ),
    ]
