# Generated by Django 2.0.6 on 2018-07-27 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0002_auto_20180727_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grout',
            name='grout_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 27, 14, 45, 0, 827782, tzinfo=utc)),
        ),
    ]
