# Generated by Django 2.0.6 on 2018-07-28 13:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grout', '0003_auto_20180727_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, max_length=500)),
                ('date', models.DateField(default=datetime.datetime(2018, 7, 28, 13, 9, 36, 909047, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='grout',
            name='grout_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 28, 13, 9, 36, 908047, tzinfo=utc)),
        ),
    ]
