# Generated by Django 2.0.6 on 2018-07-28 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0004_auto_20180728_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grout',
            name='grout_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 28, 13, 39, 30, 435631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 28, 13, 39, 30, 436631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
