# Generated by Django 2.0.6 on 2018-07-28 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0005_auto_20180728_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grout',
            name='grout_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 28, 13, 56, 51, 317166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grout',
            name='remark',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 28, 13, 56, 51, 318166, tzinfo=utc)),
        ),
    ]
