# Generated by Django 2.0.6 on 2018-07-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0006_auto_20180728_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grout',
            name='grout_date',
            field=models.DateField(default='2018-07-29'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default='2018-07-29'),
        ),
    ]
