# Generated by Django 2.0.6 on 2018-07-29 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grout', '0007_auto_20180729_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surplus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.FloatField()),
                ('amount_today', models.FloatField()),
                ('amount_sum', models.FloatField()),
                ('conversion_number', models.IntegerField()),
                ('reward', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
