# Generated by Django 2.0.6 on 2018-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0009_auto_20180729_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surplus',
            name='amount_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='surplus',
            name='amount_today',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='surplus',
            name='conversion_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surplus',
            name='remaining',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='surplus',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
