# Generated by Django 2.0.6 on 2018-07-30 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0010_auto_20180729_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grout',
            name='grout_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='surplus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
