# Generated by Django 2.0.6 on 2018-07-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0012_auto_20180730_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remaining',
            name='remain',
            field=models.FloatField(default=0),
        ),
    ]
