# Generated by Django 2.0.6 on 2018-07-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0013_auto_20180730_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplus',
            name='remaining',
            field=models.FloatField(default=0),
        ),
    ]
