# Generated by Django 2.0.6 on 2018-07-31 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0015_auto_20180731_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
