# Generated by Django 2.0.6 on 2018-07-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_auto_20180724_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Originalpile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
