# Generated by Django 2.0.6 on 2018-07-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0004_trypile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piledetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('pile_length', models.IntegerField()),
                ('pile_diameter', models.FloatField()),
                ('pipe_layer_d', models.IntegerField()),
                ('pipe_layer_c', models.IntegerField()),
                ('soil_d', models.CharField(max_length=50)),
                ('grout_amount_d', models.FloatField()),
                ('grout_amount_c', models.FloatField()),
                ('grout_amount', models.FloatField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
