# Generated by Django 2.0.5 on 2018-09-04 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Punchcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, max_length=50)),
                ('remark', models.CharField(blank=True, max_length=500)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
