# Generated by Django 2.0.6 on 2018-07-21 00:36

from django.db import migrations, models
import kaisai.models


class Migration(migrations.Migration):

    dependencies = [
        ('kaisai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaisai',
            name='image',
            field=models.ImageField(upload_to=kaisai.models.upload_kaisai_path),
        ),
    ]
